version: '3'
services:
  postgresql:
    container_name: postgresql
    image: postgres:14.1
    environment:
      - POSTGRES_USER=scrapper
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=scrapper
    ports:
      - '5432:5432'
    volumes: 
      - postgresql:/data/postgres
    networks:
      - backend
  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=scrapper
      - --password=admin
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend
networks:
  backend: {}
volumes:
  postgresql:
    driver: local